# Alpha Vantage API Exploration

This notebook contains exploration of the Alpha Vantage API.

[API Documentation](https://www.alphavantage.co/documentation)

[Python Wrapper](https://github.com/RomelTorres/alpha_vantage)

In [59]:
!pip install alpha_vantage

Requirement already satisfied: alpha_vantage in /Users/azel/anaconda3/lib/python3.7/site-packages (2.1.0)
Requirement already satisfied: requests in /Users/azel/anaconda3/lib/python3.7/site-packages (from alpha_vantage) (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/azel/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/azel/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/azel/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/azel/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (1.24.2)

In [13]:
from alpha_vantage.timeseries import TimeSeries
from decouple import config
import matplotlib.pyplot as plt
import pandas as pd

ts = TimeSeries(key=config('ALPHA_VANTAGE'), output_format='pandas')
data, meta_data = ts.get_intraday(symbol='AAPL',interval='1min', outputsize='full')
data['4. close'].plot()
plt.title('Intraday Times Series for the AAPL stock (1 min)')
plt.show()

In [2]:
data.head()

                     1. open   2. high  3. low  4. close  5. volume
date
2019-08-06 09:31:00   196.31  197.3100  196.31  197.1000  2304507.0
2019-08-06 09:32:00   197.10  197.4900  196.94  197.3900   395619.0
2019-08-06 09:33:00   197.39  197.9144  197.10  197.9144   412163.0
2019-08-06 09:34:00   197.90  198.0670  197.50  197.7800   479078.0
2019-08-06 09:35:00   197.79  197.8900  197.52  197.6650   295073.0

In [66]:
data.shape

(1945, 5)

In [14]:
dir(ts)

['_ALPHA_VANTAGE_API_URL',
 '_ALPHA_VANTAGE_DIGITAL_CURRENCY_LIST',
 '_ALPHA_VANTAGE_MATH_MAP',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_type',
 '_call_api_on_func',
 '_handle_api_call',
 '_output_format',
 '_retry',
 'get_batch_stock_quotes',
 'get_daily',
 'get_daily_adjusted',
 'get_intraday',
 'get_monthly',
 'get_monthly_adjusted',
 'get_weekly',
 'get_weekly_adjusted',
 'indexing_type',
 'key',
 'map_to_matype',
 'output_format',
 'proxy',
 'retries',
 'set_proxy',
 'treat_info_as_error']

In [17]:
data, meta_data = ts.get_daily(symbol='AAPL',outputsize='full')

data.head()

            1. open  2. high  3. low  4. close    5. volume
date
1999-08-13   2.1652   2.2143  2.1384    2.1451   74608800.0
1999-08-16   2.1362   2.1674  2.1250    2.1607   69232800.0
1999-08-17   2.1540   2.1563  2.1049    2.1540   80234000.0
1999-08-18   2.1451   2.2143  2.1295    2.1473  117143600.0
1999-08-19   2.1362   2.1607  2.0915    2.0982  137505200.0

In [13]:
data.tail()

            1. open  2. high  3. low  4. close  5. volume
date
2019-08-06    22.29    22.87   19.77     20.17        0.0
2019-08-07    20.70    23.67   18.94     19.49        0.0
2019-08-08    19.36    19.89   16.82     16.91        0.0
2019-08-09    18.14    19.44   17.31     17.97        0.0
2019-08-12    17.87    20.31   17.77     19.72        0.0

Well that is convenient. Nice clean, compact time series dataframes in pandas.

In [34]:
from alpha_vantage.techindicators import TechIndicators

ti = TechIndicators(key=config('ALPHA_VANTAGE'), output_format='pandas')

In [23]:
dir(ti)

['_ALPHA_VANTAGE_API_URL',
 '_ALPHA_VANTAGE_DIGITAL_CURRENCY_LIST',
 '_ALPHA_VANTAGE_MATH_MAP',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_type',
 '_call_api_on_func',
 '_handle_api_call',
 '_output_format',
 '_retry',
 'get_ad',
 'get_adosc',
 'get_adx',
 'get_adxr',
 'get_apo',
 'get_aroon',
 'get_aroonosc',
 'get_atr',
 'get_bbands',
 'get_bop',
 'get_cci',
 'get_cmo',
 'get_dema',
 'get_dx',
 'get_ema',
 'get_ht_dcperiod',
 'get_ht_dcphase',
 'get_ht_phasor',
 'get_ht_sine',
 'get_ht_trendline',
 'get_ht_trendmode',
 'get_kama',
 'get_macd',
 'get_macdext',
 'get_mama',
 'get_mfi',
 'get_midpoint',
 'get_midprice',
 'get_minus_di',
 'get_minus_dm',
 'get_mom',
 'get_natr',
 'get_obv',
 'get_plus_di',
 'get_plus_dm',
 'get_ppo',
 'get_roc',
 'get_rocr',
 'get_rsi',
 'get_sar',
 'get_sma',
 'get_stoch',
 'get_stochf',
 'get_stochrsi',
 'get_t3',
 'get_tema',
 'get_trange',
 'get_trima',
 'get_trix',
 'get_ultsoc',
 'get_willr',
 'get_wma',
 'indexing_type',
 'key',
 'map_to_matype',
 'output_format',
 'proxy',
 'retries',
 'set_proxy',
 'treat_info_as_error']

In [35]:
sma, extra= ti.get_sma(symbol='AAPL')
sma.head()

               SMA
date
1999-09-10  2.3432
1999-09-13  2.3699
1999-09-14  2.4008
1999-09-15  2.4277
1999-09-16  2.4575

In [53]:
extra

{'1: Symbol': 'AAPL',
 '2: Indicator': 'Simple Moving Average (SMA)',
 '3: Last Refreshed': '2019-08-13 12:53:30',
 '4: Interval': 'daily',
 '5: Time Period': 20,
 '6: Series Type': 'close',
 '7: Time Zone': 'US/Eastern'}

In [61]:
symbols = ['OBV', 'midprice', 'mfi', 'mom']

new_symbols = ["get_"+symbol.lower() for symbol in symbols]

In [65]:
for symbol in new_symbols:
    data, metadata = getattr(ti, symbol)(symbol='AAPL')
    print(data.shape)
    print(metadata)

(5032, 1)
{'1: Symbol': 'AAPL', '2: Indicator': 'On Balance Volume (OBV)', '3: Last Refreshed': '2019-08-13 13:36:22', '4: Interval': 'daily', '5: Time Zone': 'US/Eastern Time'}
(5013, 1)
{'1: Symbol': 'AAPL', '2: Indicator': 'Midpoint Price over period (MIDPRICE)', '3: Last Refreshed': '2019-08-13 13:36:22', '4: Interval': 'daily', '5: Time Period': 20, '6: Time Zone': 'US/Eastern Time'}
(5012, 1)
{'1: Symbol': 'AAPL', '2: Indicator': 'Money Flow Index (MFI)', '3: Last Refreshed': '2019-08-13 13:36:26', '4: Interval': 'daily', '5: Time Period': 20, '6: Time Zone': 'US/Eastern Time'}
(5012, 1)
{'1: Symbol': 'AAPL', '2: Indicator': 'Momentum (MOM)', '3: Last Refreshed': '2019-08-13 13:36:26', '4: Interval': 'daily', '5: Time Period': 20, '6: Series Type': 'close', '7: Time Zone': 'US/Eastern Time'}

In [18]:
data.merge(sma, how='inner', on='date')

             1. open   2. high    3. low  4. close    5. volume       SMA
date
1999-09-10    2.7143    2.7746    2.6674    2.7656  114690800.0    2.3432
1999-09-13    2.7522    2.7522    2.6719    2.6786   63000000.0    2.3699
1999-09-14    2.6685    2.8036    2.6674    2.7790   97073200.0    2.4008
1999-09-15    2.8170    2.8259    2.6875    2.6920   89894000.0    2.4277
1999-09-16    2.7165    2.7879    2.6384    2.7433  110471200.0    2.4575
1999-09-17    2.7612    2.7768    2.7232    2.7478   69319600.0    2.4900
1999-09-20    2.7500    2.8616    2.7455    2.8237  114167200.0    2.5254
1999-09-21    2.6138    2.6161    2.4643    2.4732  839389600.0    2.5406
1999-09-22    2.4911    2.5580    2.4648    2.5112  280792400.0    2.5584
1999-09-23    2.5402    2.5446    2.2500    2.2612  285938800.0    2.5618
1999-09-24    2.2634    2.3934    2.2500    2.3192  294968800.0    2.5669
1999-09-27    2.3705    2.3839    2.1853    2.1897  237048000.0    2.5607
1999-09-28    2.1964    2.2143    2.0513    2.1295  353740800.0    2.5564
1999-09-29    2.1518    2.1875    2.0714    2.1094  164320800.0    2.5453
1999-09-30    2.1272    2.2924    2.1161    2.2612  227021200.0    2.5358
1999-10-01    2.2188    2.2299    2.1250    2.2042  153697600.0    2.5200
1999-10-04    2.2277    2.3170    2.2277    2.3058  114839200.0    2.5041
1999-10-05    2.3438    2.4330    2.3125    2.4263  203551600.0    2.4890
1999-10-06    2.4777    2.4866    2.3929    2.3996  201068000.0    2.4759
1999-10-07    2.4442    2.4509    2.3170    2.3705  151471600.0    2.4595
1999-10-08    2.3638    2.3683    2.2679    2.3415   95701200.0    2.4383
1999-10-11    2.3571    2.4375    2.3571    2.3817   65780400.0    2.4235
1999-10-12    2.4241    2.4866    2.3929    2.4174  140938000.0    2.4054
1999-10-13    2.3795    2.4821    2.2768    2.2868  159182800.0    2.3852
1999-10-14    2.4732    2.6183    2.4643    2.6138  474700800.0    2.3787
1999-10-15    2.5402    2.7076    2.5067    2.6629  293294400.0    2.3744
1999-10-18    2.6384    2.6518    2.5402    2.6161  194101600.0    2.3641
1999-10-19    2.5580    2.6786    2.4442    2.4464  255645600.0    2.3627
1999-10-20    2.5000    2.6875    2.5000    2.6830  270351200.0    2.3713
1999-10-21    2.5915    2.7522    2.5848    2.7188  198363200.0    2.3942
...              ...       ...       ...       ...          ...       ...
2019-07-01  203.1700  204.4900  200.6500  201.5500   27316700.0  194.3815
2019-07-02  201.4100  203.1300  201.3600  202.7300   16935200.0  195.5360
2019-07-03  203.2800  204.4400  202.6900  204.4100   11362000.0  196.6295
2019-07-05  203.3500  205.0800  202.9000  204.2300   17265500.0  197.5800
2019-07-08  200.8100  201.4000  198.4100  200.0200   25338600.0  198.0735
2019-07-09  199.2000  201.5100  198.8100  201.2400   20578000.0  198.5065
2019-07-10  201.8500  203.7300  201.5600  203.2300   17897100.0  198.9275
2019-07-11  203.3100  204.3900  201.7100  201.7500   20191800.0  199.3055
2019-07-12  202.4500  204.0000  202.2000  203.3000   17595200.0  199.7630
2019-07-15  204.0900  205.8700  204.0000  205.2100   16947400.0  200.3865
2019-07-16  204.5900  206.1100  203.5000  204.5000   16866800.0  200.9170
2019-07-17  204.0500  205.0900  203.2700  203.3500   14107500.0  201.1620
2019-07-18  204.0000  205.8800  203.7000  205.6600   18582200.0  201.5515
2019-07-19  205.7900  206.5000  202.3600  202.5900   20929300.0  201.7080
2019-07-22  203.6500  207.2300  203.6100  207.2200   22277900.0  202.1300
2019-07-23  208.4600  208.9100  207.2900  208.8400   18355200.0  202.6430
2019-07-24  207.6700  209.1500  207.1700  208.6700   14991600.0  203.2980
2019-07-25  208.8900  209.2400  206.7300  207.0200   13909600.0  203.6590
2019-07-26  207.4800  209.7300  207.1400  207.7400   17618900.0  204.0590
2019-07-29  208.4600  210.6400  208.4400  209.6800   21673400.0  204.6470
2019-07-30  208.7600  210.1600  207.3100  208.7800   33935700.0  205.0085
2019-07-31  216.4200  221.3700  211.3000  213.0400   69281400.0  205.5240
2019-08-01  213.9000  218.0300  206.7400  208.4300   54017900.0  205.7250
2019-08-02  205.5300  206.4300  201.6300  204.0200   40862100.0  205.7145
2019-08-05  197.9900  198.6500  192.5800  193.3400   52393000.0  205.3805
2019-08-06  196.3100  198.0700  194.0400  197.0000   35824800.0  205.1685
2019-08-07  195.4100  199.5600  193.8200  199.0400   33364400.0  204.9590
2019-08-08  200.2000  203.5300  199.3900  203.4300   27009500.0  205.0430
2019-08-09  201.3000  202.7600  199.2900  200.9900   24619700.0  204.9275
2019-08-12  199.6200  202.0500  199.1500  200.4800   22474900.0  204.6910

[5012 rows x 6 columns]

In [21]:
meta_data

{'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2019-08-13 10:49:54',
 '4. Output Size': 'Full size',
 '5. Time Zone': 'US/Eastern'}

In [66]:
from alpha_vantage.foreignexchange import ForeignExchange

cc = ForeignExchange(key=config('ALPHA_VANTAGE'), 
                     output_format='pandas')

dir(cc)

['_ALPHA_VANTAGE_API_URL',
 '_ALPHA_VANTAGE_DIGITAL_CURRENCY_LIST',
 '_ALPHA_VANTAGE_MATH_MAP',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_type',
 '_call_api_on_func',
 '_handle_api_call',
 '_output_format',
 '_retry',
 'get_currency_exchange_daily',
 'get_currency_exchange_intraday',
 'get_currency_exchange_monthly',
 'get_currency_exchange_rate',
 'get_currency_exchange_weekly',
 'indexing_type',
 'key',
 'map_to_matype',
 'output_format',
 'proxy',
 'retries',
 'set_proxy',
 'treat_info_as_error']

In [76]:
??cc.get_currency_exchange_daily

Signature:
cc.get_currency_exchange_daily(
    from_symbol,
    to_symbol,
    outputsize='compact',
)
Source:
    @av._output_format
    @av._call_api_on_func
    def get_currency_exchange_daily(self, from_symbol, to_symbol, outputsize='compact'):
        """ Returns the daily exchange rate for any pair of physical
        currency (e.g., EUR) or physical currency (e.g., USD).

        Keyword Arguments:
            from_symbol: The currency you would like to get the exchange rate
                for.
                For example: from_symbol=EUR or from_symbol=USD.
            to_symbol: The destination currency for the exchange rate.
                For example: to_symbol=USD or to_symbol=JPY.
            outputsize:  The size of the call, supported values are
                'compact' and 'full; the first returns the last 100 points in the
                data series, and 'full' returns the full-length daily times
                series, commonly above 1MB (default 'compact')
        """
        _FUNCTION_KEY = 'FX_DAILY'
        return _FUNCTION_KEY, "Time Series FX (Daily)", 'Meta Data'
File:      ~/anaconda3/lib/python3.7/site-packages/alpha_vantage/foreignexchange.py
Type:      method

In [98]:
data, metadata = cc.get_currency_exchange_daily(from_symbol='USD', to_symbol='EUR', outputsize='full')

In [99]:
data

            1. open  2. high  3. low  4. close
date
2014-11-07   0.8053   0.8054  0.8019    0.8025
2014-11-09   0.8015   0.8023  0.8008    0.8021
2014-11-10   0.8021   0.8049  0.7992    0.8046
2014-11-11   0.8045   0.8045  0.7998    0.8015
2014-11-12   0.8015   0.8049  0.7999    0.8044
2014-11-13   0.8043   0.8044  0.8003    0.8013
2014-11-14   0.8014   0.8062  0.7969    0.7982
2014-11-15   0.7982   0.7982  0.7982    0.7982
2014-11-16   0.7974   0.7986  0.7973    0.7986
2014-11-17   0.7986   0.8032  0.7950    0.8029
2014-11-18   0.8030   0.8034  0.7970    0.7977
2014-11-19   0.7977   0.7989  0.7944    0.7968
2014-11-20   0.7968   0.7994  0.7951    0.7971
2014-11-21   0.7971   0.8078  0.7955    0.8070
2014-11-23   0.8080   0.8087  0.8078    0.8080
2014-11-24   0.8038   0.8048  0.8032    0.8036
2014-11-25   0.8037   0.8059  0.8008    0.8014
2014-11-26   0.8014   0.8034  0.7980    0.7993
2014-11-27   0.7993   0.8024  0.7983    0.8022
2014-11-28   0.8023   0.8044  0.8004    0.8028
2014-11-29   0.8028   0.8028  0.8028    0.8028
2014-11-30   0.8024   0.8033  0.8015    0.8031
2014-12-01   0.8031   0.8049  0.7994    0.8015
2014-12-02   0.8015   0.8077  0.8013    0.8073
2014-12-03   0.8072   0.8127  0.8067    0.8123
2014-12-04   0.8123   0.8130  0.8028    0.8076
2014-12-05   0.8076   0.8145  0.8067    0.8136
2014-12-06   0.8136   0.8136  0.8136    0.8136
2014-12-07   0.8141   0.8145  0.8134    0.8136
2014-12-08   0.8138   0.8162  0.8101    0.8117
...             ...      ...     ...       ...
2019-07-11   0.8879   0.8889  0.8859    0.8881
2019-07-12   0.8881   0.8894  0.8864    0.8867
2019-07-14   0.8869   0.8883  0.8860    0.8869
2019-07-15   0.8869   0.8883  0.8859    0.8878
2019-07-16   0.8878   0.8924  0.8874    0.8917
2019-07-17   0.8918   0.8926  0.8900    0.8905
2019-07-18   0.8902   0.8920  0.8861    0.8887
2019-07-19   0.8887   0.8922  0.8870    0.8912
2019-07-21   0.8911   0.8919  0.8902    0.8912
2019-07-22   0.8912   0.8921  0.8905    0.8919
2019-07-23   0.8919   0.8969  0.8918    0.8964
2019-07-24   0.8965   0.8982  0.8961    0.8972
2019-07-25   0.8973   0.9005  0.8937    0.8969
2019-07-26   0.8969   0.8996  0.8964    0.8984
2019-07-28   0.8987   0.8990  0.8979    0.8981
2019-07-29   0.8981   0.8995  0.8965    0.8969
2019-07-30   0.8969   0.8980  0.8957    0.8960
2019-07-31   0.8959   0.9038  0.8955    0.9023
2019-08-01   0.9023   0.9066  0.9010    0.9024
2019-08-02   0.9024   0.9030  0.8993    0.8995
2019-08-04   0.9000   0.9013  0.8980    0.9002
2019-08-05   0.9002   0.9002  0.8905    0.8906
2019-08-06   0.8906   0.8950  0.8885    0.8924
2019-08-07   0.8924   0.8942  0.8893    0.8922
2019-08-08   0.8922   0.8946  0.8904    0.8938
2019-08-09   0.8937   0.8939  0.8908    0.8920
2019-08-11   0.8940   0.8940  0.8917    0.8924
2019-08-12   0.8924   0.8956  0.8903    0.8914
2019-08-13   0.8915   0.8950  0.8901    0.8946
2019-08-14   0.8940   0.8950  0.8938    0.8949

[1504 rows x 4 columns]

In [100]:
meta_data

{'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2019-08-13 10:49:54',
 '4. Output Size': 'Full size',
 '5. Time Zone': 'US/Eastern'}

In [97]:
print('###################################################################','\n',
      'Ticker: ' , meta_data['2. Symbol'], '\n',
      'Last Refreshed: ', meta_data['3. Last Refreshed'], '\n',
      'Data Retrieved: ', meta_data['1. Information'],'\n',
      '###################################################################')

###################################################################
 Ticker:  AAPL
 Last Refreshed:  2019-08-13 10:49:54
 Data Retrieved:  Daily Prices (open, high, low, close) and Volumes
 ###################################################################